name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Debug repository contents
        run: |
          ls -la
          echo "Current directory structure:"
          find . -type f -name "*.toml" | xargs cat
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'  # Specify a stable version
          extended: true
      
      - name: Clone theme directly (bypassing submodules)
        run: |
          rm -rf themes/somrat
          mkdir -p themes
          git clone --depth 1 https://github.com/somrat-themes/somrat-hugo.git themes/somrat
          echo "Theme directory contents:"
          ls -la themes/somrat
          
      - name: Clean Hugo cache
        run: hugo --cleanDestinationDir
        
      - name: Build with Hugo
        run: |
          echo "Building site with Hugo..."
          hugo --minify
          echo "Public directory contents:"
          ls -la public
          
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
